In [1]:
import pandas as pd
from pathlib import Path
import py3Dmol
from utils import *

#### Chose a protein pair

In [2]:
PDB_id = "1AAX"
AF_id = "P18031"

#### All detected pockets
- on the left: PDB experimental structure
- on the right: AfphaFold model

In [3]:
files = get_pdb_files(PDB_id, AF_id)

structure_pdb = files["pdb"]["structure"]
structure_af = files["af"]["structure"]

out_pdb = files["pdb"]["out"]
out_af = files["af"]["out"]

pocket_files_pdb = files["pdb"]["pocket_files"]
pocket_files_af = files["af"]["pocket_files"]

print(f"Detected pockets in PDB stucture: {len(pocket_files_pdb)}.")
print(f"Detected pockets in AlphaFold model: {len(pocket_files_af)}.")

Detected pockets in PDB stucture: 17.
Detected pockets in AlphaFold model: 20.

In [4]:
view_compare = show_fpocket_comparison(
    structure_pdb, out_pdb, pocket_files_pdb,
    structure_af, out_af, pocket_files_af,
    width=700, height=500
)
view_compare.show()

#### Analysis results

In [5]:
df = prepare_df(PDB_id, AF_id)

In [6]:
prepare_status_summary(df)

       Status  Count
0     matched     10
1  weak_match      4
2    pdb_only      3
3     af_only      6

In [7]:
prepare_score_summary(df)

        PDB score  AF score  PDB drug  AF drug
mean         0.08     -0.04      0.04     0.07
median       0.05     -0.03      0.00     0.00
max          0.35      0.09      0.68     0.66

#### Best matched pockets statistics
Jaccard threshold can be changed.

In [8]:
jaccard_threshold = 0.75

In [9]:
report_df, pdb_pockets, af_pockets = best_matched(PDB_id, AF_id, jaccard_threshold)
report_df

,PDB,AF,Jaccard,RMSD,pLDDT,PDB score,AF score,PDB drug,AF drug,PDB vol,AF vol
0,5,12,1.00,0.19,98.29,0.12,-0.04,0.00,0.00,268.3,259.4
1,1,1,0.88,0.32,95.86,0.35,0.09,0.68,0.36,490.5,328.9
2,9,16,0.88,0.18,97.75,0.05,-0.08,0.00,0.00,256.7,414.1
3,2,3,0.87,0.17,98.17,0.23,0.02,0.02,0.01,679.6,575.2
4,10,5,0.86,0.09,98.70,0.05,0.01,0.00,0.00,216.8,312.2
5,16,14,0.75,0.16,98.09,-0.00,-0.05,0.00,0.00,259.6,150.5

#### View best matched pockets
- on the left: PDB experimental structure
- on the right: AfphaFold model

In [10]:
view_matched = show_fpocket_comparison(
    structure_pdb, out_pdb, pocket_files_pdb,
    structure_af, out_af, pocket_files_af,
    pdb_pockets, af_pockets,
    width=700, height=500
)
view_matched.show()

#### View chosen pair of pockets
- on the left: PDB experimental structure
- on the right: AfphaFold model

In [11]:
pdb_pocket = 1
af_pocket = 1

In [12]:
view_chosen = show_pocket_comparison(
    structure_pdb, pocket_files_pdb, pdb_pocket,
    structure_af, pocket_files_af, af_pocket,
    width=700, height=500
)
view_chosen.show()