In [59]:
import pandas as pd
from pathlib import Path
import py3Dmol
from utils import *

#### Chose a protein pair

In [60]:
PDB_id = "5GPG"
AF_id = "Q00688"

In [61]:
files = get_pdb_files(PDB_id, AF_id)

structure_pdb = files["pdb"]["structure"]
structure_af = files["af"]["structure"]

Sequence alignment measures:
- **identity** - fraction of matching residues
- **coverage** - fraction of the PDB sequence aligned

In [62]:
print_target_summary(PDB_id, AF_id)

PROTEIN INFORMATION
  Class : isomerase
  Group : likely NON-druggable
  Notes : -

Sequence alignment summary
  PDB sequence length : 110
  AF sequence length  : 116
  Identity            : 1.00%
  Coverage            : 0.99%

3D alignment summary
  Matched Cα atoms : 109
  RMSD             : 0.467 Å

**Visualization convention:**

- PDB experimental structure – *violet*
- AlphaFold model – *orange*

In [63]:
show_alignment(structure_pdb, structure_af)

#### All detected pockets
- on the left: PDB experimental structure
- on the right: AfphaFold model

In [64]:
out_pdb = files["pdb"]["out"]
out_af = files["af"]["out"]

pocket_files_pdb = files["pdb"]["pocket_files"]
pocket_files_af = files["af"]["pocket_files"]

print(f"Detected pockets in PDB stucture: {len(pocket_files_pdb)}.")
print(f"Detected pockets in AlphaFold model: {len(pocket_files_af)}.")

Detected pockets in PDB stucture: 5.
Detected pockets in AlphaFold model: 5.

In [65]:
view_compare = show_fpocket_comparison(
    structure_pdb, out_pdb, pocket_files_pdb,
    structure_af, out_af, pocket_files_af,
    width=700, height=500
)
view_compare.show()

#### Analysis results

In [66]:
df = prepare_df(PDB_id, AF_id)

In [67]:
prepare_status_summary(df)

       Status  Count
0     matched      4
1  weak_match      0
2    pdb_only      1
3     af_only      1

In [68]:
prepare_score_summary(df)

        PDB score  AF score  PDB drug  AF drug
mean         0.16      0.18      0.08     0.06
median       0.12      0.18      0.02     0.06
max          0.38      0.39      0.32     0.19

#### Best matched pockets statistics
Jaccard threshold can be changed.

In [69]:
jaccard_threshold = 0.3

In [70]:
report_df, pdb_pockets, af_pockets = best_matched(PDB_id, AF_id, jaccard_threshold)
report_df

,PDB,AF,Jaccard,RMSD,pLDDT,PDB score,AF score,PDB drug,AF drug,PDB vol,AF vol
0,4,5,1.00,0.53,88.44,0.09,0.02,0.02,0.00,333.8,256.2
1,5,2,0.88,0.20,90.59,0.07,0.19,0.02,0.07,214.3,368.1
2,3,3,0.83,0.43,76.87,0.12,0.18,0.03,0.06,258.5,191.8
3,1,1,0.71,0.24,89.57,0.38,0.39,0.32,0.19,569.5,427.3

#### View best matched pockets
- on the left: PDB experimental structure
- on the right: AfphaFold model

In [71]:
view_matched = show_fpocket_comparison(
    structure_pdb, out_pdb, pocket_files_pdb,
    structure_af, out_af, pocket_files_af,
    pdb_pockets, af_pockets,
    width=700, height=500
)
view_matched.show()

#### View chosen pair of pockets
- on the left: PDB experimental structure
- on the right: AfphaFold model

In [72]:
pdb_pocket = 1
af_pocket = 1

In [73]:
view_chosen = show_pocket_comparison(
    structure_pdb, pocket_files_pdb, pdb_pocket,
    structure_af, pocket_files_af, af_pocket,
    width=700, height=500
)
view_chosen.show()

In [74]:
view_pocket_alignment = show_pocket_alignment(structure_pdb, structure_af,
                                              pocket_files_pdb, pocket_files_af,
                                              pdb_pocket, af_pocket)
view_pocket_alignment.show()